name: DevOps Project 2 Pipeline

on: push

jobs:
  devops2-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set-up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Formatting test
        run: black --check .

      - name: Linting Test
        run: flake8 .

      - name: Static Analysis Security Test (Bandit)
        run: bandit -r . --skip B201

      - name: Unit test
        run: pytest



